"""Tests for nginx upstream rendering and rollback behavior."""

from __future__ import annotations

from pathlib import Path
import sys
import tempfile
import unittest

CURRENT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = CURRENT_DIR.parent
sys.path.insert(0, str(PROJECT_DIR))

from autoscale_agent.compose_loader import ServiceTemplate
from autoscale_agent.config import AgentSettings
from autoscale_agent.nginx_control import Backend, NginxController, render_upstream


class RenderUpstreamTest(unittest.TestCase):
    """Ensures upstream output contains configured backends."""

    def test_renders_backends(self) -> None:
        content = render_upstream(
            upstream_name="biz_service_upstream",
            backends=[
                Backend(target="biz-service:8080", comment="seed-service-dns"),
                Backend(target="172.22.0.15:8080", comment="managed testdocker-biz-service-managed-1"),
            ],
        )

        self.assertIn("upstream biz_service_upstream", content)
        self.assertIn("server biz-service:8080 max_fails=3 fail_timeout=10s;", content)
        self.assertIn("server 172.22.0.15:8080 max_fails=3 fail_timeout=10s;", content)
        self.assertIn("keepalive 32;", content)


class NginxControllerRollbackTest(unittest.TestCase):
    """Verifies nginx config rollback when validation fails."""

    def test_apply_backends_should_restore_previous_content_on_validation_failure(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            generated_dir = Path(temp_dir)
            upstream_file = generated_dir / "biz-service.upstream.inc"
            upstream_file.write_text(
                "# generated by autoscale-agent\nupstream biz_service_upstream {\n    server biz-service:8080;\n}\n",
                encoding="utf-8",
            )

            settings = AgentSettings(
                compose_file=Path("/workspace/docker-compose.yml"),
                generated_dir=generated_dir,
                target_service="biz-service",
                nginx_service="nginx",
                poll_interval_seconds=15,
                min_replicas=1,
                max_replicas=4,
                scale_up_window=2,
                scale_down_window=3,
                cooldown_seconds=60,
                drain_seconds=20,
                startup_timeout_seconds=180,
                http_timeout_seconds=2.5,
                cpu_up_threshold=70.0,
                cpu_down_threshold=25.0,
                memory_up_threshold=80.0,
                memory_down_threshold=35.0,
                app_metric_rules=(),
            )
            template = ServiceTemplate(
                project_name="testdocker",
                service_name="biz-service",
                image="testdocker-biz-service:latest",
                environment={},
                labels={},
                healthcheck=None,
                command=None,
                entrypoint=None,
                working_dir=None,
                user=None,
                target_port=8080,
                health_path="/api/health",
                metrics_path="/api/autoscale/metrics",
                upstream_name="biz_service_upstream",
                seed_host="biz-service",
            )
            controller = NginxController(settings, template, FakeDockerClient(validation_exit_code=1))

            with self.assertRaisesRegex(RuntimeError, "nginx -t failed"):
                controller.apply_backends([Backend(target="new:8080", comment="new backend")])

            restored = upstream_file.read_text(encoding="utf-8")
            self.assertIn("server biz-service:8080;", restored)


class FakeDockerClient:
    """Minimal docker client stub used by the unit test."""

    def __init__(self, validation_exit_code: int) -> None:
        self.containers = FakeContainers(validation_exit_code)


class FakeContainers:
    """Container collection stub returning one fake nginx container."""

    def __init__(self, validation_exit_code: int) -> None:
        self._validation_exit_code = validation_exit_code

    def list(self, filters):  # noqa: ANN001 - mirrors docker SDK shape.
        return [FakeNginxContainer(self._validation_exit_code)]


class FakeNginxContainer:
    """Simple stub for nginx exec calls."""

    def __init__(self, validation_exit_code: int) -> None:
        self._validation_exit_code = validation_exit_code

    def exec_run(self, command):  # noqa: ANN001 - mirrors docker SDK shape.
        if command == ["nginx", "-t"]:
            return FakeExecResult(self._validation_exit_code, b"synthetic nginx -t failure")
        return FakeExecResult(0, b"ok")


class FakeExecResult:
    """Simple exec result stub compatible with docker SDK calls."""

    def __init__(self, exit_code: int, output: bytes) -> None:
        self.exit_code = exit_code
        self.output = output


if __name__ == "__main__":
    unittest.main()
