"""Generated nginx upstream rendering and safe reload helpers."""

from __future__ import annotations

from dataclasses import dataclass
import logging
import os
from typing import Iterable

from autoscale_agent.compose_loader import ServiceTemplate
from autoscale_agent.config import AgentSettings

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class Backend:
    """One nginx upstream backend."""

    target: str
    comment: str


class NginxController:
    """Writes the upstream include file and reloads nginx safely."""

    def __init__(self, settings: AgentSettings, template: ServiceTemplate, docker_client) -> None:
        self._settings = settings
        self._template = template
        self._client = docker_client
        self._settings.generated_dir.mkdir(parents=True, exist_ok=True)

    def apply_backends(self, backends: Iterable[Backend]) -> bool:
        """Writes a new upstream config and reloads nginx when changed."""

        backend_list = list(backends)
        content = render_upstream(
            upstream_name=self._template.upstream_name,
            backends=backend_list,
        )
        existing = (
            self._settings.upstream_file.read_text(encoding="utf-8")
            if self._settings.upstream_file.exists()
            else None
        )
        if existing == content:
            return False

        backup = existing
        temp_path = self._settings.upstream_file.with_suffix(".tmp")
        temp_path.write_text(content, encoding="utf-8")
        os.replace(temp_path, self._settings.upstream_file)

        nginx_container = self._find_nginx_container()
        test_result = nginx_container.exec_run(["nginx", "-t"])
        if test_result.exit_code != 0:
            self._restore_previous_content(backup)
            output = _decode_output(test_result.output)
            raise RuntimeError(f"nginx -t failed after upstream update: {output}")

        reload_result = nginx_container.exec_run(["nginx", "-s", "reload"])
        if reload_result.exit_code != 0:
            self._restore_previous_content(backup)
            output = _decode_output(reload_result.output)
            raise RuntimeError(f"nginx reload failed after upstream update: {output}")
        LOGGER.info("Applied nginx upstream change with %s configured backends", len(backend_list))
        return True

    def _find_nginx_container(self):
        containers = self._client.containers.list(
            filters={
                "label": [
                    f"com.docker.compose.project={self._template.project_name}",
                    f"com.docker.compose.service={self._settings.nginx_service}",
                ]
            }
        )
        if not containers:
            raise RuntimeError("Running nginx container was not found.")
        return containers[0]

    def _restore_previous_content(self, previous_content: str | None) -> None:
        temp_path = self._settings.upstream_file.with_suffix(".restore")
        if previous_content is None:
            self._settings.upstream_file.unlink(missing_ok=True)
            return
        temp_path.write_text(previous_content, encoding="utf-8")
        os.replace(temp_path, self._settings.upstream_file)


def render_upstream(upstream_name: str, backends: list[Backend]) -> str:
    """Renders the nginx upstream include body."""

    lines = [
        "# generated by autoscale-agent",
        f"upstream {upstream_name} {{",
        "    least_conn;",
    ]
    if not backends:
        lines.append("    # no-healthy-backends")
        lines.append("    server 127.0.0.1:65535 down;")
    else:
        for backend in backends:
            lines.append(f"    # {backend.comment}")
            lines.append(f"    server {backend.target} max_fails=3 fail_timeout=10s;")
    lines.append("    keepalive 32;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _decode_output(raw: bytes | str | None) -> str:
    if raw is None:
        return ""
    if isinstance(raw, bytes):
        return raw.decode("utf-8", errors="replace").strip()
    return str(raw).strip()
